server {
    listen 80;
    server_name localhost;

    # Serve frontend files
    root /usr/share/nginx/html;
    index frontend/html/index.html;

    location / {
        try_files $uri $uri/ /frontend/html/index.html;
    }

        location ~* \.js$ {
        add_header Cache-Control "no-cache";
    }

    # Proxy all /api requests to the FastAPI backend
    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}